### ISSUE TITLE
Using this role sometimes apt-get throws weird errors.

### ISSUE THREAD

**Issue by bbaassssiiee** [bcoca/ansible-oracle_java7-role#7]
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  gsfonts gsfonts-x11 java-common
Suggested packages:
  default-jre equivs binfmt-support visualvm ttf-baekmuk ttf-unfonts
  ttf-unfonts-core ttf-kochi-gothic ttf-sazanami-gothic ttf-kochi-mincho
  ttf-sazanami-mincho ttf-arphic-uming firefox firefox-2 iceweasel
  mozilla-firefox iceape-browser mozilla-browser epiphany-gecko
  epiphany-webkit epiphany-browser galeon midbrowser moblin-web-browser
  xulrunner xulrunner-1.9 konqueror chromium-browser midori google-chrome
The following NEW packages will be installed:
  gsfonts gsfonts-x11 java-common oracle-java7-installer
  oracle-java7-set-default
0 upgraded, 5 newly installed, 0 to remove and 100 not upgraded.
Need to get 3540 kB of archives.
After this operation, 5461 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main oracle-java7-installer all 7u80+7u60arm-0~webupd8~1 [22.4 kB]
Get:2 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main oracle-java7-set-default all 7u80+7u60arm-0~webupd8~1 [4782 B]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main java-common all 0.51 [130 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1 [3374 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main gsfonts-x11 all 0.22 [9108 B]
Preconfiguring packages ...
Fetched 3540 kB in 10s (329 kB/s)
Selecting previously unselected package java-common.
(Reading database ... 60980 files and directories currently installed.)
Preparing to unpack .../java-common_0.51_all.deb ...
Unpacking java-common (0.51) ...
Selecting previously unselected package oracle-java7-installer.
Preparing to unpack .../oracle-java7-installer_7u80+7u60arm-0~webupd8~1_all.deb ...
Unpacking oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
Selecting previously unselected package gsfonts.
Preparing to unpack .../gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.2ubuntu1_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1) ...
Selecting previously unselected package gsfonts-x11.
Preparing to unpack .../gsfonts-x11_0.22_all.deb ...
Unpacking gsfonts-x11 (0.22) ...
Selecting previously unselected package oracle-java7-set-default.
Preparing to unpack .../oracle-java7-set-default_7u80+7u60arm-0~webupd8~1_all.deb ...
Unpacking oracle-java7-set-default (7u80+7u60arm-0~webupd8~1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Setting up java-common (0.51) ...
Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1) ...
Setting up gsfonts-x11 (0.22) ...
Setting up oracle-java7-set-default (7u80+7u60arm-0~webupd8~1) ...

fatal: [test] => Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1116, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/callbacks.py", line 547, in on_ok
    super(PlaybookRunnerCallbacks, self).on_ok(host, host_result)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/callbacks.py", line 347, in on_ok
    call_callback_module('runner_on_ok', host, res)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages/ansible/callbacks.py", line 179, in call_callback_module
    method(*args, **kwargs)
  File "/Users/bas/code/buildserver/plugins/callbacks/human_log.py", line 22, in runner_on_ok
    human_log(res)
  File "/Users/bas/code/buildserver/plugins/callbacks/human_log.py", line 11, in human_log
    print '\n{0}:\n{1}'.format(field, res[field])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 1355: ordinal not in range(128)

**Comment by bcoca** [comment]
closing via merged fix
